### ISSUE TITLE
Question: Should we fail faster when docker is not found?

### ISSUE THREAD

**Issue by seanpoulter** [webdriverio-community/wdio-docker-service#133]
Should we throw a SevereServiceError` when `docker` isn't found? Right now there's an error in the log but the tests keep running:

```
DEBUG wdio-docker-service: Docker command: docker run --cidfile .../wdio-docker-service/nginx.cid --rm -p 8080:8080 -v .../wdio-docker-service/test/integration/docker-app/app/:/usr/share/nginx/html:ro -v .../wdio-docker-service/test/integration/docker-app/nginx.conf:/etc/nginx/nginx.conf:ro --health-cmd "curl -sS http://127.0.0.1:8080 || exit 1" --health-timeout 10s --health-interval 5s nginx
WARN wdio-docker-service: Connecting dockerEventsListener: 585794
INFO wdio-docker-service: Cleaning up CID files
WARN wdio-docker-service: NOTE: Pulling image for the first time. Please be patient.
ERROR wdio-docker-service: Error: Error executing sub-child: docker events --format "{{json .}}" --filter image=nginx
/bin/sh: 1: docker: not found

    at DockerEventsListener._onMessage (/home/sean/Development/GitHub/seanpoulter/Forks/webdriverio-community/wdio-docker-service/src/utils/dockerEventsListener.js:55:27)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at emit (internal/child_process.js:935:14)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
WARN wdio-docker-service: Disconnecting dockerEventsListener: 585794
INFO chromedriver: Initiate Chromedriver Launcher (v8.1.1)

```

We suppress the `ENOENT` here:

https://github.com/webdriverio-community/wdio-docker-service/blob/efa15d3bd890d8e3c7843658f2348f986fbb63b2/src/utils/docker.js#L123-L129

**Comment by seanpoulter** [comment]
Any reason to pull in another package Christian? I thought the `ENOENT` from line 124 above already tell us.

**Comment by christian-bromann** [comment]
Looking close at the code I think it is worth to do some refactoring and instead of chaining all the promises to use `await` and handle individual errors if each call manually. Meaning, if we call the docker command, check for error and return early as you suggested.
